FROM docker.io/node:23.11.0-slim@sha256:dfb18d8011c0b3a112214a32e772d9c6752131ffee512e974e59367e46fcee52

WORKDIR /usr/app

COPY package*.json .

RUN npm ci

COPY . .

RUN printenv

CMD ["npm", "run", "dev"]