FROM docker.io/node:23.11.0-slim

WORKDIR /usr/app

COPY package*.json .

RUN npm ci

COPY tsconfig.json* nodemon.json* *.json ./

RUN apt-get -y update; apt-get -y install curl

EXPOSE 3000

CMD ["npm", "run", "dev"]